version: '2'
services:
  server:
    image: abouopensource/server_part
    networks:
      - network_1



  tiny_code:
    image: abouopensource/tiny_python
    networks:
      - network_1



networks:
  network_1:
    driver: bridge